[versions]
kotlin = "2.3.0"
shadow = "9.3.1"
publish = "2.0.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }

[libraries]
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }